/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpdeskcode;

import javax.swing.JOptionPane;
import helpers.Functions;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mukama
 */
public class AdminPanel extends javax.swing.JFrame {
    Functions saveDetails;
    ResultSet rs;
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        fillUserTaskCombo();
        fillCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userTabbedMenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        createUserBtn = new javax.swing.JButton();
        userNameInput = new javax.swing.JTextField();
        userTypeCombo = new javax.swing.JComboBox();
        serviceTimeCombo = new javax.swing.JComboBox();
        sexCombo = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        fullNameInput = new javax.swing.JTextField();
        dobInput = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        phoneInput = new javax.swing.JTextField();
        jobTitleInput = new javax.swing.JTextField();
        passwordFieldTxt = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        addOfficeBtn = new javax.swing.JButton();
        officeNameInput = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        addDeviceBtn = new javax.swing.JButton();
        deviceNameInput = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        officeIdInput = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        specDeviceTextArea = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersDataTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        userDeactivateCombo = new javax.swing.JComboBox();
        deactivateUserBtn = new javax.swing.JButton();
        devicePanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        devicesJTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        officesJTable = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        helpTaskCombo = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        assignTaskCombo = new javax.swing.JComboBox();
        assignTaskBtn = new javax.swing.JButton();
        deviceLocationCombo = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        locateTheDevice = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        saveServerBtn = new javax.swing.JButton();
        iPAddressInput = new javax.swing.JTextField();
        userNameInputServer = new javax.swing.JTextField();
        passwordServerInput = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ticketJTable = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        unSolveTicketJTable = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        knowledgeTxt = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        knowledgeTxtArea = new javax.swing.JTextArea();
        saveKnowlegeBtn = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        messagesJTable = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        aboutJOptionMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JHelpMenu = new javax.swing.JMenu();
        aboutJMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        userTabbedMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTabbedMenuMouseClicked(evt);
            }
        });

        jLabel2.setText("Welcome Admin");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 51));
        jLabel3.setText("You can use the navigation menu to perform any of the major tasks on this system");

        jLabel4.setText("Please endevour to keep system login credentials to yourself");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel4)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        userTabbedMenu.addTab("Welcome", jPanel1);

        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 3, true));

        jLabel5.setText("User Name:");

        jLabel6.setText("Service Time:");

        jLabel7.setText("Sex:");

        jLabel8.setText("Password:");

        jLabel9.setText("User Type:");

        jLabel10.setText("Job Title:");

        createUserBtn.setText("Create User");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        userTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "HelpDesk", "OfficialUser" }));

        serviceTimeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013/2014", "2014/ 2015", "2015/2016", "2016/2017" }));

        sexCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel20.setText("Full Name:");

        jLabel23.setText("Date of Birth:");

        dobInput.setToolTipText("YYYY-MM-DD");

        jLabel24.setText("Email:");

        jLabel25.setText("Phone:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(createUserBtn))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameInput)
                            .addComponent(userTypeCombo, 0, 223, Short.MAX_VALUE)
                            .addComponent(fullNameInput)
                            .addComponent(dobInput)
                            .addComponent(passwordFieldTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serviceTimeCombo, 0, 246, Short.MAX_VALUE)
                            .addComponent(sexCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailInput)
                            .addComponent(phoneInput)
                            .addComponent(jobTitleInput))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(userNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceTimeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jobTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(userTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(fullNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dobInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(createUserBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Create a New User");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        userTabbedMenu.addTab("Create Users", jPanel2);

        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 3, true));

        jLabel12.setText("Office Name:");

        addOfficeBtn.setText("Add Office");
        addOfficeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfficeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addOfficeBtn)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(officeNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(officeNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addOfficeBtn)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("Create a New Office");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(543, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(192, 192, 192)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel13)
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );

        userTabbedMenu.addTab("Register Offices", jPanel3);

        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 3, true));

        jLabel14.setText("Device Name:");

        addDeviceBtn.setText("Add Device");
        addDeviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeviceBtnActionPerformed(evt);
            }
        });

        jLabel16.setText("Office Name:");

        specDeviceTextArea.setColumns(20);
        specDeviceTextArea.setRows(5);
        specDeviceTextArea.setToolTipText("Please Enter All Properties Separated With Commas");
        jScrollPane2.setViewportView(specDeviceTextArea);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDeviceBtn)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(deviceNameInput)
                            .addComponent(officeIdInput, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(deviceNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(officeIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addDeviceBtn)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("Create a New Device");

        jLabel26.setText("Devices Specifications:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel26)))
                .addContainerGap(474, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(255, 255, 255)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(336, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel15)
                .addGap(126, 126, 126)
                .addComponent(jLabel26)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );

        userTabbedMenu.addTab("Register Devices", jPanel4);

        usersDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "User Name", "User Type", "Sex", "Status", "Job Title", "Service Term"
            }
        ));
        jScrollPane1.setViewportView(usersDataTable);

        jLabel17.setText("Registered Users");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(495, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(477, 477, 477))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        userTabbedMenu.addTab("View Users", jPanel5);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("Select User To Deactivate");

        jLabel31.setText("Select User:");

        deactivateUserBtn.setText("Deactivate User");
        deactivateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(349, 349, 349))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deactivateUserBtn)
                    .addComponent(userDeactivateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel30)
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(userDeactivateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deactivateUserBtn)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        userTabbedMenu.addTab("Deactivate Users", jPanel6);

        devicePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devicePanelMouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("List Devices");

        devicesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Device Name", "Device Properties"
            }
        ));
        jScrollPane3.setViewportView(devicesJTable);
        if (devicesJTable.getColumnModel().getColumnCount() > 0) {
            devicesJTable.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout devicePanelLayout = new javax.swing.GroupLayout(devicePanel);
        devicePanel.setLayout(devicePanelLayout);
        devicePanelLayout.setHorizontalGroup(
            devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devicePanelLayout.createSequentialGroup()
                .addGroup(devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(devicePanelLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(jLabel32))
                    .addGroup(devicePanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        devicePanelLayout.setVerticalGroup(
            devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devicePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        userTabbedMenu.addTab("Show Devices", devicePanel);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 51, 51));
        jLabel33.setText("List Offices");

        officesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Office Name"
            }
        ));
        jScrollPane4.setViewportView(officesJTable);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jLabel33))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        userTabbedMenu.addTab("Show Offices", jPanel8);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("Assign Tasks");

        jLabel28.setText("Help Desk User:");

        jLabel29.setText("Assign Task:");

        assignTaskCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignTaskComboMouseClicked(evt);
            }
        });
        assignTaskCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                assignTaskComboItemStateChanged(evt);
            }
        });

        assignTaskBtn.setText("Assign Task");
        assignTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTaskBtnActionPerformed(evt);
            }
        });

        jLabel40.setText("Device Location");

        locateTheDevice.setBackground(new java.awt.Color(0, 0, 255));
        locateTheDevice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        locateTheDevice.setForeground(new java.awt.Color(255, 255, 255));
        locateTheDevice.setText("Locate");
        locateTheDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locateTheDeviceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(375, 375, 375))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel40))
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(helpTaskCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assignTaskCombo, 0, 324, Short.MAX_VALUE)
                    .addComponent(assignTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceLocationCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locateTheDevice)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(helpTaskCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(assignTaskCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deviceLocationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(locateTheDevice))
                .addGap(19, 19, 19)
                .addComponent(assignTaskBtn)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        userTabbedMenu.addTab("Assign Tasks", jPanel9);

        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 3, true));

        jLabel18.setText("Host IP Address:");

        jLabel21.setText("User Name:");

        jLabel22.setText("Password:");

        saveServerBtn.setText("Save Configuration");
        saveServerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveServerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveServerBtn)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iPAddressInput, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(userNameInputServer)
                            .addComponent(passwordServerInput, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(iPAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(userNameInputServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(passwordServerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveServerBtn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel19.setText("Make server the server configurations are similar to the details of server computer that has the database");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        userTabbedMenu.addTab("Server Configuration", jPanel13);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("List Tickets");

        ticketJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Title", "Ticket Details", "Status", "Submission Date", "Priority", "Device Name"
            }
        ));
        jScrollPane5.setViewportView(ticketJTable);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        userTabbedMenu.addTab("Complaints", jPanel15);

        unSolveTicketJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Title", "Ticket Details", "Status", "Submission Date", "Priority", "Device Name", "Additional Information"
            }
        ));
        jScrollPane7.setViewportView(unSolveTicketJTable);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 51, 0));
        jLabel38.setText("UnSolved Issues");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jLabel38))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        userTabbedMenu.addTab("Unsolved Issues", jPanel16);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 0, 0));
        jLabel35.setText("Submit Knowlege Base:");

        jLabel36.setText("Title:");

        jLabel37.setText("Details:");

        knowledgeTxtArea.setColumns(20);
        knowledgeTxtArea.setRows(5);
        jScrollPane6.setViewportView(knowledgeTxtArea);

        saveKnowlegeBtn.setText("Save");
        saveKnowlegeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveKnowlegeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveKnowlegeBtn)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(knowledgeTxt)
                        .addComponent(jLabel35)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(knowledgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveKnowlegeBtn)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        userTabbedMenu.addTab("Knowledge Base", jPanel7);

        messagesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Title", "Details", "Sender"
            }
        ));
        jScrollPane8.setViewportView(messagesJTable);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 0, 0));
        jLabel39.setText("List All Messages");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jLabel39))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        userTabbedMenu.addTab("Messages", jPanel17);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Welcome to Help Desk Management System Admin Panel");

        aboutJOptionMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutJOptionMenuMouseClicked(evt);
            }
        });

        jMenu1.setText("File");
        aboutJOptionMenu.add(jMenu1);

        JHelpMenu.setText("Help");
        JHelpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JHelpMenuMouseClicked(evt);
            }
        });
        JHelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JHelpMenuActionPerformed(evt);
            }
        });

        aboutJMenu.setText("About");
        aboutJMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutJMenuMouseClicked(evt);
            }
        });
        aboutJMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJMenuActionPerformed(evt);
            }
        });
        JHelpMenu.add(aboutJMenu);

        aboutJOptionMenu.add(JHelpMenu);

        setJMenuBar(aboutJOptionMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userTabbedMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(118, 118, 118)
                        .addComponent(logoutBtn))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(userTabbedMenu))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutJOptionMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutJOptionMenuMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_aboutJOptionMenuMouseClicked

    private void JHelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JHelpMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JHelpMenuActionPerformed

    private void aboutJMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJMenuActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_aboutJMenuActionPerformed

    private void JHelpMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JHelpMenuMouseClicked
        // TODO add your handling code here:
       
         
    }//GEN-LAST:event_JHelpMenuMouseClicked

    private void aboutJMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutJMenuMouseClicked
        // TODO add your handling code here:
    
          JOptionPane.showMessageDialog(this,"System was Designed by the IT Team 2014/2015 as the final year project\n Thanks Our Then Supervisor Mr.Ntwari Richard");  
        
    }//GEN-LAST:event_aboutJMenuMouseClicked

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        // TODO add your handling code here:
        //this is done to pick inputs from the textfields
        String userName=userNameInput.getText().toString();
        String password=passwordFieldTxt.getText().toString();
        String sex=sexCombo.getSelectedItem().toString();
        String userType=userTypeCombo.getSelectedItem().toString();
        String serviceTime=serviceTimeCombo.getSelectedItem().toString();
        String jobTitle=jobTitleInput.getText().toString();
        String fullName=fullNameInput.getText().toString();
        String dob=dobInput.getText().toString();
        String email=emailInput.getText().toString();
        String phone=phoneInput.getText().toString();
        //check if the inputs received are not empty
        if(!userName.isEmpty() && !password.isEmpty() && !jobTitle.isEmpty() && !fullName.isEmpty() && !dob.isEmpty() && !email.isEmpty() && !email.isEmpty()){
          // all the contents picked from the form are passed in one array
            String [] details={userName,password,userType,sex,jobTitle,serviceTime,fullName,dob,email,phone};
        String [] columns={"User_Name","Password","User_Type","Sex","Job_Title","Service","Full_Names","DOB","Email","Phone"};
        String tableName="users";
        //creating an object for the functions class
        saveDetails=new Functions();
//        System.out.println("\n"+saveDetails.mergeString(columns, "User_Name,"));
//        System.out.println("\n"+saveDetails.mergeString(details, ""));
        //calling the method
         saveDetails.saveDetails(columns, details, tableName,"User_Name");
         
         userNameInput.setText("");
         passwordFieldTxt.setText("");
         fullNameInput.setText("");
         dobInput.setText("");
         emailInput.setText("");
         phoneInput.setText("");
         jobTitleInput.setText("");  
        }else{
           JOptionPane.showMessageDialog(null, "Please fill all fields and create user");
                   
        }
        
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void addOfficeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfficeBtnActionPerformed
        // TODO add your handling code here
        String officeName=officeNameInput.getText().toString();
        if(!officeName.isEmpty())
        {
            String detail=officeName;
            String column="Office_Name";
            String tableName="offices"; 
            Functions saveOffice=new Functions();
            saveOffice.saveSingleRecord(detail, column, tableName);
        }else{
            JOptionPane.showMessageDialog(null, "Enter office and save to create office");
        }
        
        officeNameInput.setText("");
    }//GEN-LAST:event_addOfficeBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        Main loginActivity=new Main();
        loginActivity.show();
        this.setVisible(false);
        
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void addDeviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeviceBtnActionPerformed
        // TODO add your handling code here:
        String recordOne=deviceNameInput.getText().toString();
        String recordThree=specDeviceTextArea.getText().toString();
        int recordTwo=officeIdInput.getSelectedIndex();
        if(!recordOne.isEmpty() && !recordThree.isEmpty()){
            String column1="Device_Name";
            String column2="Office_Id";
            String column3="Device_Properties";
            String tableName="devices";
            Functions saveDevice= new Functions();
            saveDevice.saveThreeRecords(recordOne, (recordTwo+1),recordThree ,column1, column2,column3, tableName);
            deviceNameInput.setText("");
            specDeviceTextArea.setText("");  
        }else{
           JOptionPane.showMessageDialog(null, "Please fill in fields and create a new device");
        }
        
    }//GEN-LAST:event_addDeviceBtnActionPerformed

    private void userTabbedMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTabbedMenuMouseClicked
        // TODO add your handling code here:
        //display all users
        listUsers();
        
        //display all devices
        listDevices();
        
        //display all offices
        listOffices();
        
        //display all tickets
        listTickets();
        
        //list unsolved tickets for the admin
        listUnSolvedTickets();
        
        //listing all the messages that have been sent
        listMessages();
        
        //for populating the user combo when deactivating help desk users
        fillUserCombo();
        
        //fill the task combo
        fillTaskCombo();
    }//GEN-LAST:event_userTabbedMenuMouseClicked

    private void saveServerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveServerBtnActionPerformed
        // TODO add your handling code here:
        String ipAddress=iPAddressInput.getText().toString();
        String pass=passwordServerInput.getText().toString();
        String userServerName=userNameInputServer.getText().toString();
        if(!ipAddress.isEmpty() && !pass.isEmpty() && !userServerName.isEmpty())
        {
            String [] serverDetails={ipAddress,pass,userServerName};
            String tableName="server";
            String firstColumn="Host_Ip";
            String [] columnServerNames={"Host_Ip","Password","Db_Name"};
            Functions serverInserter=new Functions();
            serverInserter.saveDetails(columnServerNames, serverDetails, tableName, firstColumn);
            iPAddressInput.setText("");
            passwordServerInput.setText("");
            userNameInputServer.setText(""); 
        }else{
            JOptionPane.showMessageDialog(null, "Please enter all fields and enter new server details");
        }
        
    }//GEN-LAST:event_saveServerBtnActionPerformed

    private void assignTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignTaskBtnActionPerformed
        // TODO add your handling code here:
        String ticketTitle=assignTaskCombo.getSelectedItem().toString();
        String userName=(helpTaskCombo.getSelectedItem().toString());
        Functions saveTask=new Functions();
        saveTask.saveTwo(ticketTitle, userName, "Ticket_Title", "User_Id", "tasks","Task Has Been Assigned Successfully To: "+userName);
    }//GEN-LAST:event_assignTaskBtnActionPerformed

    private void deactivateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateUserBtnActionPerformed
        // TODO add your handling code here:
        String userName=userDeactivateCombo.getSelectedItem().toString();
        String sql="update users set Status='Deactivated' where User_Name='"+userName+"';";
        Functions deactivateUsers=new Functions();
        deactivateUsers.updateTable(sql, "User Has Been Deactivated");
    }//GEN-LAST:event_deactivateUserBtnActionPerformed

    private void devicePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devicePanelMouseClicked
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_devicePanelMouseClicked

    private void saveKnowlegeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveKnowlegeBtnActionPerformed
        // TODO add your handling code here:
        String kTitle=knowledgeTxt.getText().toString();
        String kBody=knowledgeTxtArea.getText().toString();
        if(!kTitle.isEmpty() && !kBody.isEmpty())
        {
            Functions saveKnowlege=new Functions();
            saveKnowlege.saveTwo(kBody, kTitle, "Knowledge_Details", "Knowledge_Title", "knowledge_base", "Knowledge Base Saved Successfully");
            knowledgeTxt.setText("");
            knowledgeTxtArea.setText("");
        }else{
          JOptionPane.showMessageDialog(null, "Please fill in all fields");
        }
        
    }//GEN-LAST:event_saveKnowlegeBtnActionPerformed

    private void assignTaskComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_assignTaskComboItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_assignTaskComboItemStateChanged

    private void assignTaskComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignTaskComboMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_assignTaskComboMouseClicked

    private void locateTheDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locateTheDeviceActionPerformed
        // TODO add your handling code here:
        String taskString =assignTaskCombo.getSelectedItem().toString();
        fillDeviceCombo(taskString);
    }//GEN-LAST:event_locateTheDeviceActionPerformed
// list all users
    public void listUsers()
    {
        Functions viewUsers =new Functions();
        String userSql="select * from users";
        DefaultTableModel usersModel=(DefaultTableModel) usersDataTable.getModel();
        usersModel.setRowCount(0);
        try {
            ResultSet rs=viewUsers.showRecords(userSql);
            while(rs.next())
            {
                String no=rs.getString("User_Id");
                String userName=rs.getString("User_Name");
                String userType=rs.getString("User_Type");
                String sex=rs.getString("Sex");
                String status=rs.getString("Status");
                String course=rs.getString("Job_Title");
                String service=rs.getString("Service");
                usersModel.addRow(new Object[]{no,userName,userType,sex,status,course,service});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


//list all devices
    public void listDevices()
    {
        Functions listDevices =new Functions();
        String userSql="select * from devices";
        DefaultTableModel deviceModel=(DefaultTableModel) devicesJTable.getModel();
        deviceModel.setRowCount(0);
        try {
            ResultSet rs=listDevices.showRecords(userSql);
            while(rs.next())
            {
                String no=rs.getString("Device_Id");
                String deviceName=rs.getString("Device_Name");
                String deviceProperties=rs.getString("Device_Properties");
                deviceModel.addRow(new Object[]{no,deviceName,deviceProperties});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    //list all offices...
    
    public void listOffices()
    {
        Functions listOffices =new Functions();
        String userSql="select * from offices";
        DefaultTableModel officesModel=(DefaultTableModel) officesJTable.getModel();
        officesModel.setRowCount(0);
        try {
            ResultSet rs=listOffices.showRecords(userSql);
            while(rs.next())
            {
                String no=rs.getString("Office_Id");
                String officeName=rs.getString("Office_Name");
                officesModel.addRow(new Object[]{no,officeName});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void listTickets()
    {
        Functions listTickets =new Functions();
        String ticketsSql="select t.Ticket_Title,t.Ticket_Details,t.Status,t.Priority_Level,t.Date,d.Device_Name from tickets t,devices d where d.Device_Id=t.Device_Id ORDER BY Priority_Level ASC";
        DefaultTableModel ticketModel=(DefaultTableModel) ticketJTable.getModel();
        ticketModel.setRowCount(0);
        try {
            ResultSet rs=listTickets.showRecords(ticketsSql);
            while(rs.next())
            {
                String no=rs.getString("Ticket_Title");
                String ticketDetails=rs.getString("Ticket_Details");
                String status=rs.getString("Status");
                String priorityLevel=rs.getString("Priority_Level");
                String date=rs.getString("Date");
                String deviceName=rs.getString("Device_Name");
                ticketModel.addRow(new Object[]{no,ticketDetails,status,date,priorityLevel,deviceName});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void fillDeviceCombo(String ticketTitle)
    {
        
        try{
                Connection conn=DataBaseConnection.getConnection();
                
                String sql = "Select Device_Location from tickets where Ticket_Title='"+ticketTitle+"' ";
                Statement stmt= conn.prepareStatement(sql);
                rs= stmt.executeQuery(sql);
               deviceLocationCombo.removeAllItems();
                  while(rs.next())
                  {
                     String addname=rs.getString("Device_Location");
                     deviceLocationCombo.addItem(addname);
                      //String ob=sexSelect.getSelectedItem();
                    }
                    
        }
           catch(Exception e){
               System.out.println(e);

    }
    }
    
    //list all messages
    public void listMessages()
    {
        Functions listMessages =new Functions();
        String messagesSql="select * from messages";
        DefaultTableModel messagesModel=(DefaultTableModel) messagesJTable.getModel();
        messagesModel.setRowCount(0);
        try {
            ResultSet rs=listMessages.showRecords(messagesSql);
            while(rs.next())
            {
                String no=rs.getString("message_id");
                String title=rs.getString("message_title");
                String body=rs.getString("message_body");
                String sender=rs.getString("message_sender");
                messagesModel.addRow(new Object[]{no,title,body,sender});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void listUnSolvedTickets()
    {
        Functions listTickets =new Functions();
        String ticketsSql="select t.Ticket_Title,t.Ticket_Details,t.Status,t.Priority_Level,t.Date,d.Device_Name,t.Additional_Info from tickets t,devices d where d.Device_Id=t.Device_Id and t.Status='Not Fixed' ORDER BY Priority_Level ASC";
        DefaultTableModel ticketModel=(DefaultTableModel) unSolveTicketJTable.getModel();
        ticketModel.setRowCount(0);
        try {
            ResultSet rs=listTickets.showRecords(ticketsSql);
            while(rs.next())
            {
                String no=rs.getString("Ticket_Title");
                String ticketDetails=rs.getString("Ticket_Details");
                String status=rs.getString("Status");
                String priorityLevel=rs.getString("Priority_Level");
                String date=rs.getString("Date");
                String deviceName=rs.getString("Device_Name");
                String additionalInfo=rs.getString("Additional_Info");
                ticketModel.addRow(new Object[]{no,ticketDetails,status,date,priorityLevel,deviceName,additionalInfo});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /*
    *this method is used to 
    */
    private void fillCombo()
    {
        
        try{
                Connection conn=DataBaseConnection.getConnection();
                
                String sql = "Select Office_Name from offices";
                Statement stmt= conn.prepareStatement(sql);
                rs= stmt.executeQuery(sql);

                  while(rs.next())
                  {
                     String addname=rs.getString("Office_Name");
                     officeIdInput.addItem(addname);
                      //String ob=sexSelect.getSelectedItem();
                    }
                    
        }
           catch(Exception e){
               System.out.println(e);

    }
    }
    private void fillUserCombo()
    {
        
        try{
                Connection conn=DataBaseConnection.getConnection();
                
                String sql = "Select User_Name from users where User_Type='HelpDesk'";
                Statement stmt= conn.prepareStatement(sql);
                rs= stmt.executeQuery(sql);
                userDeactivateCombo.removeAllItems();
                  while(rs.next())
                  {
                     String addname=rs.getString("User_Name");
                     userDeactivateCombo.addItem(addname);
                      //String ob=sexSelect.getSelectedItem();
                    }
                    
        }
           catch(Exception e){
               System.out.println(e);

    }
    }
    //this is used to fill the combo box
    private void fillUserTaskCombo()
    {
        
        try{
                Connection conn=DataBaseConnection.getConnection();
                
                String sql = "Select User_Name from users where User_Type='HelpDesk'";
                Statement stmt= conn.prepareStatement(sql);
                rs= stmt.executeQuery(sql);

                  while(rs.next())
                  {
                     String addname=rs.getString("User_Name");
                     helpTaskCombo.addItem(addname);
                      //String ob=sexSelect.getSelectedItem();
                    }
                    
        }
           catch(Exception e){
               System.out.println(e);

    }
    }
     private void fillTaskCombo()
    {
        
        try{
                Connection conn=DataBaseConnection.getConnection();
                
                String sql = "Select Ticket_Title from tickets where Status='Not Fixed'";
                Statement stmt= conn.prepareStatement(sql);
                rs= stmt.executeQuery(sql);
                assignTaskCombo.removeAllItems();

                  while(rs.next())
                  {
                     String addname=rs.getString("Ticket_Title");
                     assignTaskCombo.addItem(addname);
                      //String ob=sexSelect.getSelectedItem();
                    }
                    
        }
           catch(Exception e){
               System.out.println(e);

    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JHelpMenu;
    private javax.swing.JMenu aboutJMenu;
    private javax.swing.JMenuBar aboutJOptionMenu;
    private javax.swing.JButton addDeviceBtn;
    private javax.swing.JButton addOfficeBtn;
    private javax.swing.JButton assignTaskBtn;
    private javax.swing.JComboBox assignTaskCombo;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JButton deactivateUserBtn;
    private javax.swing.JComboBox deviceLocationCombo;
    private javax.swing.JTextField deviceNameInput;
    private javax.swing.JPanel devicePanel;
    private javax.swing.JTable devicesJTable;
    private javax.swing.JTextField dobInput;
    private javax.swing.JTextField emailInput;
    private javax.swing.JTextField fullNameInput;
    private javax.swing.JComboBox helpTaskCombo;
    private javax.swing.JTextField iPAddressInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jobTitleInput;
    private javax.swing.JTextField knowledgeTxt;
    private javax.swing.JTextArea knowledgeTxtArea;
    private javax.swing.JButton locateTheDevice;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable messagesJTable;
    private javax.swing.JComboBox officeIdInput;
    private javax.swing.JTextField officeNameInput;
    private javax.swing.JTable officesJTable;
    private javax.swing.JPasswordField passwordFieldTxt;
    private javax.swing.JTextField passwordServerInput;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JButton saveKnowlegeBtn;
    private javax.swing.JButton saveServerBtn;
    private javax.swing.JComboBox serviceTimeCombo;
    private javax.swing.JComboBox sexCombo;
    private javax.swing.JTextArea specDeviceTextArea;
    private javax.swing.JTable ticketJTable;
    private javax.swing.JTable unSolveTicketJTable;
    private javax.swing.JComboBox userDeactivateCombo;
    private javax.swing.JTextField userNameInput;
    private javax.swing.JTextField userNameInputServer;
    private javax.swing.JTabbedPane userTabbedMenu;
    private javax.swing.JComboBox userTypeCombo;
    private javax.swing.JTable usersDataTable;
    // End of variables declaration//GEN-END:variables
}
