/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpdeskcode;

import helpers.Functions;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mukama
 */
public class HelpDeskPanel extends javax.swing.JFrame {
ResultSet rs;
//SendSMS sendMyMessage=new SendSMS();
String usernameResolvedTxt;
    /**
     * Creates new form HelpDeskPanel
     */
    public HelpDeskPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userNameResolveTxt = new javax.swing.JTextField();
        confirmResolvedBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        resolvedTicketCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        statusResolvedCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resolvedAdditionalTxtArea = new javax.swing.JTextArea();
        confirmResolveBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        confirmUserNameBtn = new javax.swing.JButton();
        searchUserNameTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        yourTasksJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        knowledgeBaseHdUserJTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        messageTitleTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        messageBodyTxtArea = new javax.swing.JTextArea();
        sendMessageBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        senderTxt = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        messageDetailTxt = new javax.swing.JTextArea();
        phoneMessageTxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        sendMessagePhoneBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutHdUserBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        hdUserJMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel12.setText("Welcome HD User");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 51));
        jLabel13.setText("You can use the navigation menu to perform any of the major tasks on this system");

        jLabel14.setText("Please endevour to keep system login credentials to yourself");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel14)))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addGap(36, 36, 36)
                .addComponent(jLabel13)
                .addGap(48, 48, 48)
                .addComponent(jLabel14)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Welcome", jPanel2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Issues");

        jLabel5.setText("User Name:");

        confirmResolvedBtn.setText("Confirm");
        confirmResolvedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmResolvedBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Ticket Title:");

        jLabel7.setText("Status:");

        statusResolvedCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fixed", "Not Fixed" }));

        jLabel8.setText("Addition Information:");

        resolvedAdditionalTxtArea.setColumns(20);
        resolvedAdditionalTxtArea.setRows(5);
        jScrollPane2.setViewportView(resolvedAdditionalTxtArea);

        confirmResolveBtn.setText("Confirm");
        confirmResolveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmResolveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(userNameResolveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(31, 31, 31)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmResolveBtn)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(resolvedTicketCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusResolvedCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(confirmResolvedBtn)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userNameResolveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmResolvedBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(resolvedTicketCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(statusResolvedCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmResolveBtn)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Issues", jPanel3);

        jLabel3.setText("Enter User Name and Confirm:");

        confirmUserNameBtn.setText("Confirm");
        confirmUserNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmUserNameBtnActionPerformed(evt);
            }
        });

        yourTasksJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Title", "Ticket Details", "Status", "Priority Level", "Submission Date", "Device", "Location"
            }
        ));
        jScrollPane1.setViewportView(yourTasksJTable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Your Tasks:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(searchUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmUserNameBtn))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(confirmUserNameBtn)
                    .addComponent(searchUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Show Tasks", jPanel5);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Knowledge Base");

        knowledgeBaseHdUserJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Title", "Details"
            }
        ));
        jScrollPane4.setViewportView(knowledgeBaseHdUserJTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Knowledge Base", jPanel6);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("Send a Message");

        jLabel19.setText("Message Title:");

        jLabel20.setText("Message Body:");

        messageBodyTxtArea.setColumns(20);
        messageBodyTxtArea.setRows(5);
        jScrollPane5.setViewportView(messageBodyTxtArea);

        sendMessageBtn.setText("Send Message");
        sendMessageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageBtnActionPerformed(evt);
            }
        });

        jLabel21.setText("Sender:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendMessageBtn)
                    .addComponent(jLabel19)
                    .addComponent(messageTitleTxt)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane5)
                    .addComponent(jLabel21)
                    .addComponent(senderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(269, 269, 269))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(9, 9, 9)
                .addComponent(senderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendMessageBtn)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contact Admin", jPanel7);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Send SMS");

        jLabel24.setText("Message:");

        messageDetailTxt.setColumns(20);
        messageDetailTxt.setRows(5);
        jScrollPane6.setViewportView(messageDetailTxt);

        jLabel25.setText("Phone");

        sendMessagePhoneBtn.setText("Send");
        sendMessagePhoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessagePhoneBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(jLabel23))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendMessagePhoneBtn)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneMessageTxt)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)))))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel23)
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneMessageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addComponent(sendMessagePhoneBtn)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Send SMS", jPanel8);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Welcome to Help Desk Management System HD User Panel");

        logoutHdUserBtn.setText("Logout ");
        logoutHdUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutHdUserBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        hdUserJMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        hdUserJMenu.setText("About");
        hdUserJMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hdUserJMenuMouseClicked(evt);
            }
        });
        jMenu2.add(hdUserJMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(108, 108, 108)
                .addComponent(logoutHdUserBtn)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutHdUserBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutHdUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutHdUserBtnActionPerformed
        // TODO add your handling code here:
        Main logoutUser=new Main();
        logoutUser.show();
        this.setVisible(false);
    }//GEN-LAST:event_logoutHdUserBtnActionPerformed

    private void hdUserJMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hdUserJMenuMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"System was Designed by the IT Team 2014/2015 as the final year project\n Thanks Our Then Supervisor Mr.Ntwari Richard");
    }//GEN-LAST:event_hdUserJMenuMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"System was Designed by the IT Team 2014/2015 as the final year project\n Thanks Our Then Supervisor Mr.Ntwari Richard");
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        //listing all case lists
        listKnowledgeBase();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void sendMessagePhoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessagePhoneBtnActionPerformed
        // TODO add your handling code here:
        String myMessage=messageDetailTxt.getText().toString();
        String phone=phoneMessageTxt.getText().toString();
        if(!myMessage.isEmpty() && !phone.isEmpty())
        {
            SendSMS.init();
            SendSMS.server = "http://127.0.0.1:8800/";
            SendSMS.user = "admin";
            SendSMS.password = "admin";
            SendSMS.phonenumber = phone;
            SendSMS.text = myMessage;
            SendSMS.send();
            messageDetailTxt.setText("");
            phoneMessageTxt.setText(""); 
        }else{
            JOptionPane.showMessageDialog(null, "Please Fill in all fields to proceed");
        }
        

    }//GEN-LAST:event_sendMessagePhoneBtnActionPerformed

    private void sendMessageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageBtnActionPerformed
        // TODO add your handling code here:
        String msgTitle=messageTitleTxt.getText().toString();
        String msgBody=messageBodyTxtArea.getText().toString();
        String sender=senderTxt.getText().toString();
        if(!msgBody.isEmpty() && !msgTitle.isEmpty() && !sender.isEmpty())
        {
            //String ArrayValues[]={msgTitle,msgBody,sender};
            //String tableColumns[]={"message_title","message_body","message_sender"};
            String tableName="messages";
            Functions save=new Functions();
            save.sendMessage(msgTitle, msgBody, sender, "message_title", "message_body", "message_sender", tableName, "Message Successfully Sent.");
            messageBodyTxtArea.setText("");
            messageTitleTxt.setText("");
            senderTxt.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Please Fill in All fields To Proceed");
        }
        
    }//GEN-LAST:event_sendMessageBtnActionPerformed

    private void confirmUserNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmUserNameBtnActionPerformed
        // TODO add your handling code here:
        String userName=searchUserNameTxt.getText().toString();
        if(!userName.isEmpty())
        {
         listHDTask(userName);   
        }else{
          JOptionPane.showMessageDialog(null, "Enter User Name To Proceed");
        }
        
    }//GEN-LAST:event_confirmUserNameBtnActionPerformed

    private void confirmResolveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmResolveBtnActionPerformed
        // TODO add your handling code here:
        //submitting a resolved case
        
        String caseResolved=resolvedTicketCombo.getSelectedItem().toString();
        String status=statusResolvedCombo.getSelectedItem().toString();
        String additionalInformation=resolvedAdditionalTxtArea.getText().toString();
        if(!caseResolved.isEmpty()&& !additionalInformation.isEmpty())
        {
          String sql="update tickets set Status='"+status+"',Additional_Info='"+additionalInformation+"' where Ticket_Title='"+caseResolved+"'";
        String fetchContact="select * from tickets where Ticket_Title='"+caseResolved+"'";
        
        Functions saveResolved=new Functions();
        String date=saveResolved.getCurrentTimeStamp();
        String updateTaskLog="update task_log set Resolved='"+date+"' where Task='"+caseResolved+"'";
        
        saveResolved.saveTwoNoMessage(caseResolved, additionalInformation, "Knowledge_Title", "Knowledge_Details", "knowledge_base");
         if(status=="Fixed")
        {
            try{
                saveResolved.updateTableNoMessage(updateTaskLog);
                ResultSet rs=saveResolved.showRecords(fetchContact);
                if(rs.next())
                {
                    String phone=rs.getString("Contact");
                    String currentUser=rs.getString("Submitted_By");
                    String myMessage="Dear "+currentUser+", The MUST HelpDesk team is happy to inform that your issue has been resolved('"+caseResolved+"'). Keep using the HelpDesk system for any issues. Thanks";
                    SendSMS.init();
                    SendSMS.server = "http://127.0.0.1:8800/";
                    SendSMS.user = "admin";
                    SendSMS.password = "admin";
                    SendSMS.phonenumber = phone;
                    SendSMS.text = myMessage;
                    SendSMS.send();
                    
                }
            }catch (Exception e)
            {
               e.printStackTrace();
            }
            
        }else{
            //do nothing at all
        }
        saveResolved.updateTable(sql, "Case Marked as '"+status+"'. Details Sent to the Admin");
        resolvedAdditionalTxtArea.setText("");  
        }else{
           JOptionPane.showMessageDialog(null, "Please Fill in all fields");
        }
        

    }//GEN-LAST:event_confirmResolveBtnActionPerformed

    private void confirmResolvedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmResolvedBtnActionPerformed
        // TODO add your handling code here:
        //if this button is clicked, then populate the combo for the tasks given to the user in question
        usernameResolvedTxt=userNameResolveTxt.getText().toString();
        fillResolvedTaskCombo(usernameResolvedTxt);
        userNameResolveTxt.setText("");
    }//GEN-LAST:event_confirmResolvedBtnActionPerformed

    //populating the combo for the case list
    private void fillResolvedTaskCombo(String userName)
    {
        
        try{
                Connection conn=DataBaseConnection.getConnection();
                
                String sql = "Select t.Ticket_Title from tasks t,tickets ti where t.User_Id='"+userName+"' and ti.Status='Not Fixed' and ti.Ticket_Title=t.Ticket_Title";
                Statement stmt= conn.prepareStatement(sql);
                rs= stmt.executeQuery(sql);
                resolvedTicketCombo.removeAllItems();
                  while(rs.next())
                  {
                     String addname=rs.getString("Ticket_Title");
                     resolvedTicketCombo.addItem(addname);
                      //String ob=sexSelect.getSelectedItem();
                    }
                    
        }
           catch(Exception e){
               System.out.println(e);

    }
    }
    
//    private void fillUnResolvedTaskCombo(String userName)
//    {
//        
//        try{
//                Connection conn=DataBaseConnection.getConnection();
//                
//                String sql = "Select t.Ticket_Title from tasks t,tickets ti where t.User_Id='"+userName+"' and ti.Status='Not Fixed'";
//                Statement stmt= conn.prepareStatement(sql);
//                rs= stmt.executeQuery(sql);
//
//                  while(rs.next())
//                  {
//                     String addname=rs.getString("Ticket_Title");
//                     ticketUnresolvedCombo.addItem(addname);
//                      //String ob=sexSelect.getSelectedItem();
//                    }
//                    
//        }
//           catch(Exception e){
//               System.out.println(e);
//
//    }
//    }
    
    public void listHDTask(String userName)
    {
        Functions listTickets =new Functions();
        String hdSql="select t.Device_Location,t.Ticket_Title,t.Ticket_Details,t.Status,t.Priority_Level,t.Date,d.Device_Name from tickets t,devices d,tasks ta where d.Device_Id=t.Device_Id"
                + " and ta.Ticket_Title=t.Ticket_Title and ta.User_Id='"+userName+"'";
        DefaultTableModel hdModel=(DefaultTableModel) yourTasksJTable.getModel();
        hdModel.setRowCount(0);
        
        try {
            ResultSet rs=listTickets.showRecords(hdSql);
            while(rs.next())
            {
                String no=rs.getString("Ticket_Title");
                String ticketDetails=rs.getString("Ticket_Details");
                String status=rs.getString("Status");
                String priorityLevel=rs.getString("Priority_Level");
                String date=rs.getString("Date");
                String deviceName=rs.getString("Device_Name");
                String locateDevice=rs.getString("Device_Location");
                hdModel.addRow(new Object[]{no,ticketDetails,status,date,priorityLevel,deviceName,locateDevice});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //fill the knowledgebase
    public void listKnowledgeBase()
    {
        Functions listKB =new Functions();
        String kbSql="select * from knowledge_base";
        DefaultTableModel kbModel=(DefaultTableModel) knowledgeBaseHdUserJTable.getModel();
        kbModel.setRowCount(0);
        try {
            ResultSet rs=listKB.showRecords(kbSql);
            while(rs.next())
            {
                String no=rs.getString("Knowledge_Id");
                String kbTitle=rs.getString("Knowledge_Title");
                String kbDetails=rs.getString("Knowledge_Details");
                kbModel.addRow(new Object[]{no,kbTitle,kbDetails});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpDeskPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpDeskPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpDeskPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpDeskPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpDeskPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmResolveBtn;
    private javax.swing.JButton confirmResolvedBtn;
    private javax.swing.JButton confirmUserNameBtn;
    private javax.swing.JMenuItem hdUserJMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable knowledgeBaseHdUserJTable;
    private javax.swing.JButton logoutHdUserBtn;
    private javax.swing.JTextArea messageBodyTxtArea;
    private javax.swing.JTextArea messageDetailTxt;
    private javax.swing.JTextField messageTitleTxt;
    private javax.swing.JTextField phoneMessageTxt;
    private javax.swing.JTextArea resolvedAdditionalTxtArea;
    private javax.swing.JComboBox resolvedTicketCombo;
    private javax.swing.JTextField searchUserNameTxt;
    private javax.swing.JButton sendMessageBtn;
    private javax.swing.JButton sendMessagePhoneBtn;
    private javax.swing.JTextField senderTxt;
    private javax.swing.JComboBox statusResolvedCombo;
    private javax.swing.JTextField userNameResolveTxt;
    private javax.swing.JTable yourTasksJTable;
    // End of variables declaration//GEN-END:variables
}
