/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpdeskcode;

import helpers.Functions;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mukama
 */
public class OtherUsersPanel extends javax.swing.JFrame {
    ResultSet rs;
    Functions save=null;
    int theUserId;
    
    
    /**
     * Creates new form OtherUsersPanel
     */
    public OtherUsersPanel() {
       
        initComponents();
        fillTicketCombo();
        fillUserCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ticketSubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticketTxtArea = new javax.swing.JTextArea();
        ticketCombo = new javax.swing.JComboBox();
        sendTicketBtn = new javax.swing.JButton();
        priorityCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        userNameCombo = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        clientContact = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        officeCombo = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        knowledgeBaseJTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        resolvedCases = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        userNameSearch = new javax.swing.JTextField();
        previewIssuesBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        allCasesJTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        userSearchIssues = new javax.swing.JTextField();
        allIssuesBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutOfficialBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        officialUserJMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel2.setText("Welcome Admin");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 51));
        jLabel3.setText("You can use the navigation menu to perform any of the major tasks on this system");

        jLabel4.setText("Please endevour to keep system login credentials to yourself");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel4)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Welcome", jPanel1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Submit a Ticket");

        jLabel6.setText("Subject:");

        jLabel7.setText("Ticket Details:");

        jLabel8.setText("Select Device:");

        ticketTxtArea.setColumns(20);
        ticketTxtArea.setRows(5);
        jScrollPane1.setViewportView(ticketTxtArea);

        sendTicketBtn.setText("Send Ticket");
        sendTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendTicketBtnActionPerformed(evt);
            }
        });

        priorityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Low", "Moderate", "High" }));

        jLabel9.setText("Priority Level");

        jLabel13.setText("User Name:");

        clientContact.setToolTipText("Format: 0700000000");

        jLabel16.setText("Phone Number:");

        jLabel17.setText("Office");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel13)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(officeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priorityCombo, 0, 357, Short.MAX_VALUE)
                            .addComponent(sendTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ticketSubject)
                            .addComponent(jScrollPane1)
                            .addComponent(ticketCombo, 0, 357, Short.MAX_VALUE)
                            .addComponent(clientContact))))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ticketSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ticketCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priorityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(11, 11, 11)
                        .addComponent(officeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendTicketBtn)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Submit An Issue", jPanel2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Knowledge Base");

        knowledgeBaseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Title", "Details"
            }
        ));
        jScrollPane2.setViewportView(knowledgeBaseJTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Knowledge Base", jPanel3);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("List of All Resolved Issues");

        resolvedCases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Title", "Ticket Details", "Status", "Submission Date", "Priority", "Device Name", "Additional Information"
            }
        ));
        jScrollPane7.setViewportView(resolvedCases);

        jLabel14.setText("User Name");

        previewIssuesBtn.setText("Preview Issues");
        previewIssuesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewIssuesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(389, 389, 389))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previewIssuesBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(userNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previewIssuesBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Resolved Issues", jPanel4);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("All Issues You Submitted");

        allCasesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Title", "Ticket Details", "Status", "Submission Date", "Priority", "Device Name", "Additional Information"
            }
        ));
        jScrollPane8.setViewportView(allCasesJTable);

        jLabel15.setText("User Name:");

        allIssuesBtn.setText("Preview All Issues");
        allIssuesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allIssuesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userSearchIssues, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addComponent(allIssuesBtn)
                .addGap(307, 307, 307))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSearchIssues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(allIssuesBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Issues Submitted", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1089, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Send SMS", jPanel6);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Welcome to Help Desk Management System User Panel");

        logoutOfficialBtn.setText("Logout");
        logoutOfficialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutOfficialBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        officialUserJMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        officialUserJMenu.setText("Help");
        officialUserJMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                officialUserJMenuMouseClicked(evt);
            }
        });
        jMenu2.add(officialUserJMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(142, 142, 142)
                .addComponent(logoutOfficialBtn)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logoutOfficialBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutOfficialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutOfficialBtnActionPerformed
        // TODO add your handling code here:
        Main logoutUser= new Main();
        logoutUser.show();
        this.setVisible(false);
    }//GEN-LAST:event_logoutOfficialBtnActionPerformed

    private void officialUserJMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_officialUserJMenuMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"System was Designed by the IT Team 2014/2015 as the final year project\n Thanks Our Then Supervisor Mr.Ntwari Richard");
    }//GEN-LAST:event_officialUserJMenuMouseClicked

    private void sendTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendTicketBtnActionPerformed
        // TODO add your handling code here:
        String ticketSub=ticketSubject.getText().toString();
        String details=ticketTxtArea.getText().toString();
        String tickCombo=""+(ticketCombo.getSelectedIndex()+1);
        String priorityLevel=priorityCombo.getSelectedItem().toString();
        String userName=userNameCombo.getSelectedItem().toString();
        String contact=clientContact.getText().toString();
        String officeComboString=officeCombo.getSelectedItem().toString();
        if(!tickCombo.isEmpty() && !ticketSub.isEmpty() && !details.isEmpty() && !contact.isEmpty())
        {
            String ticketDetails[]={ticketSub,details,tickCombo,priorityLevel,"1",userName,contact,officeComboString};
            String tableFields[]={"Ticket_Title","Ticket_Details","Device_Id","Priority_Level","User_Id","Submitted_By","Contact","Device_Location"};
            String tableName="tickets";
            save=new Functions();
            Main getUsersId=new Main();
            theUserId =getUsersId.getUserId();
            //JOptionPane.showMessageDialog(null, "This is the userId: "+ theUserId);

            save.saveDetails(tableFields, ticketDetails, tableName, "Ticket_Title");
            ticketSubject.setText("");
            ticketTxtArea.setText("");
            clientContact.setText(""); 
        }else{
            JOptionPane.showMessageDialog(null, "Please Fill in all fields");
        }
        
       
    }//GEN-LAST:event_sendTicketBtnActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        // list knowledge base for the different users
        listKnowledgeBase();
        
        //for filling offices combo
        fillOfficesCombo();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void previewIssuesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewIssuesBtnActionPerformed
        // TODO add your handling code here:
       String userName=userNameSearch.getText().toString();
       if(!userName.isEmpty()){
          listResolvedTickets(userName); 
       }else{
           JOptionPane.showMessageDialog(null, "Enter User Name to Proceed");
       }
        
        userNameSearch.setText("");
        
    }//GEN-LAST:event_previewIssuesBtnActionPerformed

    private void allIssuesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allIssuesBtnActionPerformed
        // TODO add your handling code here:
        String userName=userSearchIssues.getText().toString();
        if(!userName.isEmpty()){
          listAllTickets(userName);  
        }else{
            JOptionPane.showMessageDialog(null, "Enter User Name to Proceed");
        }
        
        userSearchIssues.setText("");
    }//GEN-LAST:event_allIssuesBtnActionPerformed
//fill the knowledgebase
    public void listKnowledgeBase()
    {
        Functions listKB =new Functions();
        String kbSql="select * from knowledge_base";
        DefaultTableModel kbModel=(DefaultTableModel) knowledgeBaseJTable.getModel();
        kbModel.setRowCount(0);
        try {
            ResultSet rs=listKB.showRecords(kbSql);
            while(rs.next())
            {
                String no=rs.getString("Knowledge_Id");
                String kbTitle=rs.getString("Knowledge_Title");
                String kbDetails=rs.getString("Knowledge_Details");
                kbModel.addRow(new Object[]{no,kbTitle,kbDetails});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtherUsersPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtherUsersPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtherUsersPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtherUsersPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
               
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtherUsersPanel().setVisible(true);
            }
        });
        
    }
    
    private void fillUserCombo()
    {
        
        try{
                Connection conn=DataBaseConnection.getConnection();
                
                String sql = "Select User_Name from users where User_Type='OfficialUser'";
                Statement stmt= conn.prepareStatement(sql);
                rs= stmt.executeQuery(sql);

                  while(rs.next())
                  {
                     String addname=rs.getString("User_Name");
                     userNameCombo.addItem(addname);
                      //String ob=sexSelect.getSelectedItem();
                    }
                    
        }
           catch(Exception e){
               System.out.println(e);

    }
    }
    
    public void listResolvedTickets(String userName)
    {
        Functions listTickets =new Functions();
        String ticketsSql="select t.Ticket_Title,t.Ticket_Details,t.Status,t.Priority_Level,t.Date,d.Device_Name,t.Additional_Info from tickets t,devices d where d.Device_Id=t.Device_Id and t.Status='Fixed'"
                + "and t.Submitted_By='"+userName+"'";
        DefaultTableModel ticketModel=(DefaultTableModel) resolvedCases.getModel();
        ticketModel.setRowCount(0);
        try {
            ResultSet rs=listTickets.showRecords(ticketsSql);
            while(rs.next())
            {
                String no=rs.getString("Ticket_Title");
                String ticketDetails=rs.getString("Ticket_Details");
                String status=rs.getString("Status");
                String priorityLevel=rs.getString("Priority_Level");
                String date=rs.getString("Date");
                String deviceName=rs.getString("Device_Name");
                String additionalInfo=rs.getString("Additional_Info");
                ticketModel.addRow(new Object[]{no,ticketDetails,status,date,priorityLevel,deviceName,additionalInfo});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void listAllTickets(String userName)
    {
        Functions listTickets =new Functions();
        String ticketsSql="select t.Ticket_Title,t.Ticket_Details,t.Status,t.Priority_Level,t.Date,d.Device_Name,t.Additional_Info from tickets t,devices d where d.Device_Id=t.Device_Id "
                + "and t.Submitted_By='"+userName+"'";
        DefaultTableModel ticketModel=(DefaultTableModel) allCasesJTable.getModel();
        ticketModel.setRowCount(0);
        try {
            ResultSet rs=listTickets.showRecords(ticketsSql);
            while(rs.next())
            {
                String no=rs.getString("Ticket_Title");
                String ticketDetails=rs.getString("Ticket_Details");
                String status=rs.getString("Status");
                String priorityLevel=rs.getString("Priority_Level");
                String date=rs.getString("Date");
                String deviceName=rs.getString("Device_Name");
                String additionalInfo=rs.getString("Additional_Info");
                ticketModel.addRow(new Object[]{no,ticketDetails,status,date,priorityLevel,deviceName,additionalInfo});
            }
            //usersModel.fireTableDataChanged();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillTicketCombo()
    {
        
        try{
                Connection conn=DataBaseConnection.getConnection();
                
                String sql = "Select Device_Name from devices";
                Statement stmt= conn.prepareStatement(sql);
                rs= stmt.executeQuery(sql);

                  while(rs.next())
                  {
                     String addname=rs.getString("Device_Name");
                     ticketCombo.addItem(addname);
                      //String ob=sexSelect.getSelectedItem();
                    }
                    
        }
           catch(Exception e){
               System.out.println(e);

    }
    }
    
    private void fillOfficesCombo()
    {
        
        try{
                Connection conn=DataBaseConnection.getConnection();
                
                String sql = "Select Office_Name from offices";
                Statement stmt= conn.prepareStatement(sql);
                rs= stmt.executeQuery(sql);
                officeCombo.removeAllItems();
                  while(rs.next())
                  {
                     String addname=rs.getString("Office_Name");
                     officeCombo.addItem(addname);
                      //String ob=sexSelect.getSelectedItem();
                    }
                    
        }
           catch(Exception e){
               System.out.println(e);

    }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allCasesJTable;
    private javax.swing.JButton allIssuesBtn;
    private javax.swing.JTextField clientContact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable knowledgeBaseJTable;
    private javax.swing.JButton logoutOfficialBtn;
    private javax.swing.JComboBox officeCombo;
    private javax.swing.JMenuItem officialUserJMenu;
    private javax.swing.JButton previewIssuesBtn;
    private javax.swing.JComboBox priorityCombo;
    private javax.swing.JTable resolvedCases;
    private javax.swing.JButton sendTicketBtn;
    private javax.swing.JComboBox ticketCombo;
    private javax.swing.JTextField ticketSubject;
    private javax.swing.JTextArea ticketTxtArea;
    private javax.swing.JComboBox userNameCombo;
    private javax.swing.JTextField userNameSearch;
    private javax.swing.JTextField userSearchIssues;
    // End of variables declaration//GEN-END:variables
}
